### ISSUE TITLE
Port of Webform Import

### ISSUE THREAD

**Issue by Graham-72** [backdrop-ops/contrib#103] opened 2015-07-24 14:00 UTC
I have started porting this simple module that will provide a capability to import data from a CSV file into Backdrop through use of a webform.

I have a project where I need to get the membership details for a club of about 150 members from a spreadsheet and into Backdrop fields, so I am hoping that this will enable me to do it.

Perhaps one day someone will port the Feeds module?

**Comment by klonos** [comment] 2015-07-24 22:53
> Perhaps one day someone will port the Feeds module?

...or [Feed Import](https://www.drupal.org/project/feed_import) (no dependency on [Feeds](https://www.drupal.org/project/feeds))

**Comment by Graham-72** [comment] 2015-07-25 04:08
>> ...or Feed Import (no dependency on Feeds)

Interesting! And much less code than Feeds.
And there is a worked example at https://www.drupal.org/node/2285537

Perhaps a suitable project for a wet weekend :smiley:

**Comment by yorkshire-pudding** [comment] 2022-08-29 07:32
Looks like this should be closed as duplicate of https://github.com/backdrop-ops/contrib/issues/378

**Comment by olafgrabienski** [comment] 2022-08-29 09:20
Agreed! The module has been ported, btw - I've changed the labels of the other issue accordingly.

Link to the module: https://github.com/backdrop-contrib/webform_import

**Closed by olafgrabienski** 2022-08-29 09:20 UTC
Labels: Port in progress
