### ISSUE TITLE
Contrib Group Application: leeksoup + ISBN2node

### ISSUE THREAD

**Issue by leeksoup** [backdrop-ops/contrib#751] opened 2024-02-12 06:10 UTC
Hello and welcome to the contrib application process! We're happy to have you :)

**Please indicate how you intend to help the Backdrop community by joining this group**
* Option 1: I would like to contribute a project

## Based on your selection above, please provide the following information:

**(option 1) The name of your module, theme, or layout**
ISBN2node

## (option 1) Please note these 3 requirements for new contrib projects:

- [x] Include a README.md file containing license and maintainer information.
- [x] Include a LICENSE.txt file.
- [x] If porting a Drupal 7 project, Maintain the Git history from Drupal.

**(option 1 -- optional) Post a link here to an issue in the drupal.org queue notifying the Drupal 7 maintainers that you are working on a Backdrop port of their project**
https://www.drupal.org/project/isbn2node/issues/3420738

**Post a link to your new Backdrop project under your own GitHub account (option 1)**
https://github.com/leeksoup/ISBN2node

**(option 2) If you have already contributed code to Backdrop core or contrib projects, please provide 1-3 links to pull requests or commits**
https://github.com/backdrop-contrib/webform_import/pulls?q=is%3Apr+author%3Aleeksoup+is%3Aclosed
https://github.com/backdrop-contrib/fontyourface/pulls?q=is%3Apr+author%3Aleeksoup+is%3Aclosed

**If you have chosen option 2 or 1 above, do you agree to the [Backdrop Contributed Project Agreement](https://github.com/backdrop-ops/contrib#backdrop-contributed-project-agreement)**
YES

**Comment by argiepiano** [comment] 2024-03-07 03:13
@leeksoup thanks for porting this. I don't have enough privileges to approve your application, but I did take a quick look at the port. Looks good! A few points:
- In `hook_uninstall()` it's not necessary to do `config_clear` - all config files associated with the module will be automatically removed from the `files/config_XXX/active folder` anyways 
- Likewise, in `hook_uninstall()` there is no need to do `field_delete_field()` of `field_delete_instance()`. When you delete the node type that uses those fields, the fields are removed (unless those fields have been used in OTHER content types).
- `hook_help()` is dead code in Backdrop. It doesn't do anything, so you can remove it.
- Consider doing `include_once 'isbn2node.internal.inc';` instead of implementing hook_init to include the file. I think it's less efficient...
- The use of `config_set` within `isbn2node_settings_form_submit()` is not really needed, since you are declaring `$form['#config'] = 'isbn2node.settings';`. The values will be automatically inserted into the config file upon submission.
- You are using one argument in `isbn2node_add_form($isbn = '')` - but this is a form builder invoked by `backdrop_get_form`, meaning that the first argument will ALWAYS be $form, and the second $form_state. If you want to pass another argument to this form builder, you have to include it in the array in the `'page arguments'` key in the hook_menu implementation. I'm not sure if what you are doing actually works as intended.

**Comment by leeksoup** [comment] 2024-03-07 03:21
@argiepiano - Thank you for the code review. All those items came over from the D7 module or from Coder Upgrade, but I will fix them.

**Comment by leeksoup** [comment] 2024-03-07 03:40
OK, one more question, @argiepiano 
> If you want to pass another argument to this form builder, you have to include it in the array in the 'page arguments' key in the hook_menu implementation.

I'm not sure I understand. Looking at https://docs.backdropcms.org/api/backdrop/core%21includes%21form.inc/function/backdrop_get_form/1 it appears to me that any additional parameters beyond the $form_id are passed on to backdrop_build_form via the $form_state.

**Comment by argiepiano** [comment] 2024-03-07 03:52
> The only other thing that that function does is print a message. Should I keep the function just to do that, then, or can it be removed?

Yes, that's possible and pretty common.

> How would I specify an additional parameter to the 'page arguments' key?

The problem I see is that $isbn is never really passed to the form builder. If you look at the menu item:

```php
  $items['node/add/isbn2node-book/isbn2node'] = array(
    'title' => 'Look up by ISBN',
    'description' => 'Enter the ISBN for a book and populate an ISBN-book record based on the data fetched.',
    'page callback' => 'backdrop_get_form',
    'page arguments' => array('isbn2node_add_form'),
    'type' => MENU_NORMAL_ITEM | MENU_LOCAL_TASK,
    'access arguments' => array('add by isbn'),
    'weight' => 10,
  );
```
... there are no parameters passed to `isbn2node_add_form()`. So the form never receives anything. In fact the first parameter it receives is the $form array. The correct way to define a form builder is

`function isbn2node_add_form($form, &$form_state) {}` 

$form and $form_state will ALWAYS be passed to the form builder. IF you want to pass an isbn number, then that will be the third parameter, as in:

`function isbn2node_add_form($form, &$form_state, $isbn = '') {}`

And, to pass that parameter you have to specify it in the path when you define the menu item, as in:

```php
  $items['node/add/isbn2node-book/isbn2node/%'] = array(
    'title' => 'Look up by ISBN',
    'description' => 'Enter the ISBN for a book and populate an ISBN-book record based on the data fetched.',
    'page callback' => 'backdrop_get_form',
    'page arguments' => array('isbn2node_add_form', 4),
    'type' => MENU_NORMAL_ITEM | MENU_LOCAL_TASK,
    'access arguments' => array('add by isbn'),
    'weight' => 10,
  );
```

The above takes a parameter in the path (specified by the placeholder `%`) and sends it to the form builder as the third parameter.

You can have BOTH menu item definitions, as in:

```php
  $items['node/add/isbn2node-book/isbn2node'] = array(
    'title' => 'Look up by ISBN',
    'description' => 'Enter the ISBN for a book and populate an ISBN-book record based on the data fetched.',
    'page callback' => 'backdrop_get_form',
    'page arguments' => array('isbn2node_add_form'),
    'type' => MENU_NORMAL_ITEM | MENU_LOCAL_TASK,
    'access arguments' => array('add by isbn'),
    'weight' => 10,
  );

  $items['node/add/isbn2node-book/isbn2node/%'] = array(
    'title' => 'Look up by ISBN',
    'description' => 'Enter the ISBN for a book and populate an ISBN-book record based on the data fetched.',
    'page callback' => 'backdrop_get_form',
    'page arguments' => array('isbn2node_add_form', 4),
    'type' => MENU_NORMAL_ITEM | MENU_LOCAL_TASK,
    'access arguments' => array('add by isbn'),
    'weight' => 10,
  );
```

The above will assure that you can either use the path `node/add/isbn2node-book/isbn2node` without an isbn (in which case the $isbn parameter will be assigned `$isbn = ''` as default), OR ``node/add/isbn2node-book/isbn2node/0385121679` in which case you are passing the ISBN for the book _The Shining_ to the form builder.

**Comment by leeksoup** [comment] 2024-03-07 04:21
Thanks! I understand now. It worked fine because the user has to enter the ISBN into the form before submitting it, so the default value entered via the parameters was never used in any of my testing.

I have fixed all the issues you found, and cleaned up some minor stuff.

**Comment by jenlampton** [comment] 2024-03-07 05:58
Hi @leeksoup, and welcome! Thank you so much for your contribution :) Thank you also @argiepiano for your thorough review!  

There are only 3 requirements for new contrib projects:

- [x] Include a README.md file containing license and maintainer information.
- [x] Include a LICENSE.txt file.
- [ ] If porting a Drupal 7 project, Maintain the Git history from Drupal.

It looks like you've got #1 and #2 completed, but some of the Drupal 7 project history appears to have been lost. In particular, the comit `3ebf6164` by [vertikal.dk](https://git.drupalcode.org/vertikal.dk) on June 9, 2011, seems to be missing, or maybe more accurately, replaced by `118a9e7`: "Bringing this repo into sync with the last Drupal release." 

It could be tricky to try to restore a single commit in the history, but here's what I would do: 

- create a new `7.x` branch from the `9f569d32` commit: `git checkout -b 7.x 9f569d32`
- add the Drupal upstream as a new remote (if you don't have it already) `git remote add drupal https://git.drupalcode.org/project/ISBN2node.git`
- Pull from the Drupal upstream to pull in the missing commit: `git pull drupal 7.x-1.3`  (this should leave you with a complete drupal history on the `7.x` branch!)

Then:
- switch back to the Backdrop `1.x-1.x` branch `git checkout 1.x-1.x`
- Merge in the `7.x` branch to see if it will pull across the missing commit, in the proper sequence: `git merge 7.x` (you will probabaly have merge conflicts, but I suspect they won't be too difficult to resolve because the Drupal commit should be merged in first, and the second conflicting one can defer to what's in HEAD)

If that doesn't work or if it gives you trouble, feel free to ask for help here :)

**Comment by argiepiano** [comment] 2024-03-07 13:44
@jenlampton thanks for the official comment. Forgive me for adding to the discussion, but I'm looking at the commits in the original repository, and am noticing that all of them are there, including the one you refer. In the original D7 repository that commit is  actually `118a9e7`, not `3ebf6164` as you say. Where did you get that commit ID from?

Original:
<img width="1067" alt="Screen Shot 2024-03-07 at 6 41 09 AM" src="https://github.com/backdrop-ops/contrib/assets/9938978/28c91b5f-8fe1-4418-80fe-d901e5d8018c">

Ported:
<img width="1280" alt="Screen Shot 2024-03-07 at 6 41 23 AM" src="https://github.com/backdrop-ops/contrib/assets/9938978/e439a44d-4ae0-4cde-b90f-a7f7e97ffd0a">

**Comment by leeksoup** [comment] 2024-03-07 19:18
@argiepiano - I thought the same. I pulled the latest from the Drupal git before beginning my porting work. For some reason, the Drupal git repo didn't have the latest released version, so I added a commit to bring them to the same point.
Now I am confused ...

**Comment by jenlampton** [comment] 2024-03-07 19:30
The code changes are there, the problem is that the author of the work was
lost. The commit you added to being the backdrop repository up to date
needs to be replaced by the actual commits to the original project. The
reason we maintain history slis so that all credit for the original work
remains with the original author.

**Comment by jenlampton** [comment] 2024-03-07 19:53
> For some reason, the Drupal git repo didn't have the latest released version

It's there, it was just on a different branch. 

Here's the problem commit: https://github.com/leeksoup/ISBN2node/commit/118a9e751cb479340087aaa64544367b30b6f492

Those same changes appear in this commit: 
https://git.drupalcode.org/project/isbn2node/-/commit/3ebf6164fba0a4423bb7b9428ac9b4f2c54c82cd

If you view the [history of the Backdrop project](https://github.com/leeksoup/ISBN2node/commits), the commit `3ebf6164` is not present. 

If you don't want all of the changes that were present in that commit, the removal of those items can be done in a follow-up commit authored by you, but the original work should be credited to the original author.

I hope that helps?

**Comment by leeksoup** [comment] 2024-03-07 20:00
@jenlampton - Thanks! That explains how I overlooked it before. I'll merge that in.

**Comment by leeksoup** [comment] 2024-03-07 21:26
@jenlampton - OK, it's done. I ended up using rebase to get the commit in the right place.

**Comment by jenlampton** [comment] 2024-03-07 22:17
Thanks so much @leeksoup! An invitation should be on it's way to your inbox :)

Once you have accepted the invitation, feel free to [transfer the repository](https://docs.backdropcms.org/documentation/after-your-application-is-accepted) into the backdrop-contrib group at any time (ask here if you have questions).

---

I did ask about this problem specifically in today's weekly developer meeting, and everyone agreed that something this trivial (a single commit, and a change to the readme file, at that!) is not worth blocking anyone's entry to the contrib group. There are likely going to be a handful of Drupal modules with messy commit histories, and it's not your fault that the module you are working on has one. So, if you hadn't been able to restore that commit, we would have extended the invite anyway.  

Thank you for doing that :)

**Comment by leeksoup** [comment] 2024-03-09 02:32
Thanks @jenlampton! That's good to know for the future. 

I transferred the repo over and have a couple of questions:

1. The docs page you linked stated that I need to tag each release. For a ported project, would I give the first Backdrop release a number after the last D7 one? Or start over at 1.0.0? 
2. And is the third digit required? (I had made one last month and tagged it 1.x-1.4.)
3. Is the About info on the repo pulled from the Readme, or is it set somewhere else?

**Comment by jenlampton** [comment] 2024-03-09 23:26
If the port is identical to the 7.x version, then I usually use the same
version number, so if it was 7.x-1.4 for Drupal, it would be 1.x-1.4.0 for
Backdrop.

If it includes additional bug-fixes or minor improvements, I'd increment
the bug-fix number, so 1.x-1.4.1. if it's got major new features, I might
increment the feature number, so 1.x-1.5.0. I would not recommend
restarting the release number entirely, as that can be confusing for people
coming from Drupal and trying to compare versions.

I think all contrib projects use semantic versioning, so the third digit is
standard. I don't think it's required, technically, but it's recommended :)

The about info on the repo can be set on the repo itself, it is not pulled
from the readme. I believe there's an edit option in the GitHub right side
bar?

**Comment by jenlampton** [comment] 2024-03-11 17:27
> Would you mind also adding me as a maintainer to webform_import?

I'd love that! PR merged, and admin access granted. Sorry I missed the PR :) Thank you! 

So happy to have you as part of the contrib group!  Closing this issue as resolved, but feel free to open new issues as needed :)

**Closed by jenlampton** 2024-03-11 17:27 UTC
Labels: Maintainer application
