### ISSUE TITLE
Proposed Trigger Actions module

### ISSUE THREAD

**Issue by Graham-72** [backdrop-ops/contrib#204] opened 2017-03-13 08:37 UTC
I am working on a new module which I am calling 'Trigger Actions' (trigger_actions) which takes the functions of the D7 Trigger module and matches them with the Actions in Backdrop, and allows for the creation of new actions that are not in core. In particular I need a 'Send Email' action as in D7 and I intend to provide this as part of trigger_actions.
I will publish this as a contributed module as soon as I have a working prototype.

**Comment by docwilmot** [comment] 2017-03-13 12:06
Why not call it Trigger?

**Comment by Graham-72** [comment] 2017-03-13 13:15
What I am finding is that the new module has to include some 'actions' functions that were in D7 but are not in BD. I don't think it would be easy to directly migrate a D7 Trigger module installation to Backdrop because of changes to the actions API, so I thought I would use the new name to avoid false expectations.

**Comment by docwilmot** [comment] 2017-03-13 13:31
> the new module has to include some 'actions' functions

Yes, I looked into doing this a couple weeks ago actually, and went through all the code that would be required. Youll need to extend core Actions a bit.

But from my recollection, the "Trigger" bits would essentially be unchanged. That at least was my thinking then, not sure how realistic that is.

**Comment by klonos** [comment] 2017-03-14 16:26
As I side-note (and I think I've already mentioned this before), I see the inability to create a simple action that sends emails a feature regression from D7. I also recall that we need this functionality for the upcoming forum.b.org so that people receive email notifications upon post updates. Any reason why you are not implementing this as a core feature (that could possibly get in in 1.7)?

**Comment by Graham-72** [comment] 2017-03-14 17:31
Maybe if it proves successful and useful as a contrib module it can be promoted to core? Do you envisage we might add the triggers to core?

**Comment by klonos** [comment] 2017-03-14 18:57
I do not care for implementation at this point. It could be adding the "almighty" Rules (which I know @jenlampton hates 😄 ) in core or reintroducing the "humble" trigger/actions. What I care is bringing back the basic functionality of being able to easily setup email notifications that was removed from D7 to Backdrop 1.0.0.

**Comment by docwilmot** [comment] 2017-03-14 19:40
@Graham-72 one of the complaints about Trigger was that there was no way to make the trigger conditional. I had a thought while looking into this that maybe we could either copy or implement Layout Conditions somehow.

**Comment by Graham-72** [comment] 2017-03-14 22:11
@docwilmot - conditional triggers - that is a very interesting thought.

**Comment by klonos** [comment] 2017-03-15 19:08
Yeah, we don't have any metrics of features of D7 core so to know how many people were actually using trigger.module, but we have many legit use cases where it is required in order to achieve very basic tasks. What bothers me is that the reason it is missing from Backdrop is because it was removed from D8 core which we happened to fork from.

D8 is suggesting Rules as an alternative (which counts 300k installations), but it is not ported for Backdrop yet (and my guess is it would take a lot of effort and time because it is a "big" one). So, this makes this another blocker for people considering to move to Backdrop. I can't help but thinking that the easy and fast way would be to just get the D7 trigger.module back in core. This would be another small step in making the transition to Backdrop more seamless. Once trigger is back in core, we can refactor it so that triggers are conditional. A "light" version of Rules if you like.

**Comment by klonos** [comment] 2017-03-15 19:11
...by the way, I don't know how much refactoring has been done, but what was removed from Drupal core got a "home" in contrib: https://www.drupal.org/project/trigger

**Comment by Graham-72** [comment] 2017-03-15 20:04
@klonos yes, I am re-using the code from the D7 trigger module but reworking it to work with the actions and API in Backdrop, where there are significant differences from D7. Progress is good but I think I will spend an extra few days adding conditional triggers e.g. only apply this trigger for this specified type of node, or this individual node. Possible conditions will of course depend on the nature of the trigger.

**Comment by docwilmot** [comment] 2017-03-15 20:44
> we don't have any metrics ... to know how many people were actually using trigger.

I would suspect that is also a reason to keep it in contrib. 
I think we should put it in contrib and fix it (add conditions etc) and get those metrics, then add it back in core once it's proven itself.

**Comment by Graham-72** [comment] 2017-03-15 21:50
>  add it back in core once it's proven itself.

👍

**Comment by klonos** [comment] 2017-03-15 21:59
> >  add it back in core once it's proven itself.
> 
> 👍 

Yes, but this blocks people already using trigger.module to upgrade their sites from D7 to Backdrop. Whereas if we get trigger back in core (without any improvements; just the stock D7; only modified to work with config and current Backdrop core), we'd unblock those considering Backdrop. Not to mention that we also need it for the forum: https://github.com/backdrop-ops/forum.backdropcms.org/issues/10

IIRC, the trigger module was disabled by default in core. We can introduce it in the same state.

**Comment by jenlampton** [comment] 2017-03-15 22:11
Or trigger could exist in contrib.

**Comment by klonos** [comment] 2017-03-17 23:37
Yep, thought of that too, but we propose that people disable **and uninstall** core modules that have been removed from Backdrop CMS (see Step 2: "Prepare your Drupal site for upgrade", point 4 in https://backdropcms.org/upgrade-from-drupal). Wouldn't that remove any configured triggers and so people would have to re-create them?

**Comment by Graham-72** [comment] 2017-04-07 15:59
I have now published an initial release on Github at https://github.com/backdrop-contrib/trigger_actions/releases/tag/1.x-1.0.0.
It will work to send an email when site content is added, updated or deleted which meets my immediate need. I am not sure how much extra people would find useful. Comments welcome.

**Comment by docwilmot** [comment] 2017-04-07 16:07
Didnt bother with conditions?

**Comment by Graham-72** [comment] 2017-04-07 17:40
@docwilmot yes I did. You can set an action to only be triggered for a specific type of node, or for a specific nid. Do you think any other options might be useful? e.g class of user, or specific user?

**Comment by docwilmot** [comment] 2017-04-07 19:31
@Graham-72 havent had a chance to install and run it yet, but from looking, I have suggestions: 

We should change `node_ID` into `entity_id` instead. It would be great to be able to extend the conditions to all entities (where it makes sense) and not special-case nodes.

Ideally, however, I think better store two condition fields in the database: "condition type" and "condition id". For an NID condition then we'd store "condition type: entity_id", and "condition id: THE NID".

Then make use of something similar to the Layout access plugins code to load a list of available conditions for each entity type. So if you're creating a node action, you load a `entity_id_trigger_access` plugin or whatever and show the appropriate form and options, ie a select list to choose the condition type (node type, or nid, etc).

Also, instead of recreating the exact D7 actions style, could this use core actions instead/as well? And use `actions_execute()` instead of `trigger_actions_do()`?

Finally could the actions be stored in config instead of a database?

**Comment by Graham-72** [comment] 2017-04-08 05:42
@docwilmot Thanks for your comments.
> Finally could the actions be stored in config instead of a database?

Yes, I would prefer to use config and initially started to do so, but then remembered a comment I received elsewhere https://github.com/backdrop-contrib/simple_access_grants/issues/12 and thought that since I was including per node information I had better stick with the database. 
Is there some guidance somewhere on exactly what can or cannot be stored in config?

**Comment by jenlampton** [comment] 2018-08-04 20:00
It looks like the trigger actions module is here: https://github.com/backdrop-contrib/trigger_actions
Can we close this issue?

**Closed by jenlampton** 2018-08-04 20:00 UTC
Labels: Idea
