### ISSUE TITLE
Backdrop geo kit

### ISSUE THREAD

**Issue by ghost** [backdrop-ops/contrib#125] opened 2016-01-06 20:59 UTC
I've made an initial port of a collection of drupal mapping projects : geophp, geocoder, geofield, and leaflet. All were straightforward, except geocoder, which is marked with the infamous “dependencies[] = ctools”. I followed the @jenlampton method in the addressfield project, and it works...
That's located at https://github.com/gifad/backdrop-geokit

**Comment by quicksketch** [comment] 2016-01-07 20:29
Wow, awesome @gifad! Would you be interested in moving those modules (probably as individual projects) over into the https://github.com/backdrop-contrib group? We'd love to have official versions of all these modules.

If I get a chance, I'd love to read over your CTools porting job.

For every project, we'd require at least the following is done:

- [ ] Include a LICENSE.txt file that indicates the code is GPL v2. You can use [this copy](https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/LICENSE.txt).
- [ ] Include a README.md file that includes license and maintainer information. You can use [this example](https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/README.md).
- [ ] Maintain the Git history from Drupal 7. See [this article](http://tag1consulting.com/blog/how-maintain-contrib-modules-drupal-and-backdrop-same-time-part-2).

---

If you can get that done for any one of the modules, we can grant you access to the backdrop-contrib group and then you can transfer the projects over. You'll probably have to make a separate repository for each project so that it's D7 history may be maintained.

**Comment by gifad** [comment] 2016-01-07 23:58
I'm sorry I'm going to disappoint you, but I have no abilities to go much farther in those projects;
First, I'm not a native english speaker, and, for instance, the article about "How to Maintain Contrib Modules for Drupal and Backdrop at the Same Time" is in my bookmarks for a couple of months, but I could not yet succeed in just read it entirely;
Second, I do cms development as a hobby, just to help friends at nonprofit organizations in my neighborhood to have a decent website; I've been a software engineer in a previous life, so I still have some skills, but languages like php are completely foreign to me, github is a hostile environment, etc...
So I'm really willing to contrib, but "Maintain the Git history" or such, I just can't...
For instance, I could bring back the missing CKEditor Save and Divarea plugins in a contrib module in less than five minutes, but it took me four hours to debug a non-functionning drupal_alter() using the "deprecated" `$context3` parameter; I of course checked
`function backdrop_alter($type, &$data, &$context1 = NULL, &$context2 = NULL, &$context3 = NULL)`
but the cause was in drupal.inc : 
`function drupal_alter($type, &$data, &$context1 = NULL, &$context2 = NULL) {`
`  return backdrop_alter($type, $data, $context1, $context2);`
`}`
and this is labeled "Compatibility layer" !
No, really, I don't understand...

On the CTools front, my "CTools porting job" is not mine : it's just Jen's idea to move the individual `plugin descriptors` from the plugins to a global `plugins descriptor` in the caller module (just move back the ending 's'...)

**Comment by earthday47** [comment] 2016-01-12 21:26
hello @quicksketch and @gifad , I am very interested in this set of modules, so I would be willing to help continue work on these and maintain the repo.

**Comment by gifad** [comment] 2016-01-12 23:48
Hello @earthday47 , I fully agree your request to port my work to a professional level (which is beyond my skills).
Two caveats though : 
1 - The code is based on "latest dev" as of June 2015, with most, but not all, patches committed since applied, plus some uncommitted patches (currently in "needs review" state) - I did not keep track of those patches, so the "Maintain the Git history from Drupal 7" task will be tricky...
2 - The Leaflet configuration includes some optional plugins, manually integrated in `leaflet.drupal.js` and `leaflet_markercluster.drupal.js` (which overrides `leaflet.drupal.js` when the leaflet_markercluster module is installed); If Backdrop is willing to provide the required libraries, that's fine, else the installation guide won't be easy (to write and to read...);
It depends on how the community appreciate the final result...
You can see it live at http://p1347.phpnet.org/backdrop/l/3rgz8UIEd0Vd/node/17 - the code base there is rsync'ed to the github repo above..
In french, I'd say "bon courage"; google translates into "good luck", but there is some work, too...

**Comment by jenlampton** [comment] 2016-02-04 18:28
Hello @earthday47, and thanks for your interest in working on the geo-suite of modules! Let's see if we can help @glfad move them into the contrib group, and get you on your way :)

@glfad - If you can follow the three steps @quicksketch mentioned in his post (add two files, and maintain git history) then we can grant you access to the contrib repo, where you can move all your projects. The trickiest part might be maintaining the git history if you had started from -dev tarballs instead of a git checkout from drupal.org. Perhaps ask in IRC or on https://gitter.im/backdrop/backdrop-issues if you need help with that.

**Comment by earthday47** [comment] 2016-02-04 18:42
hi all, I've been working on getting these modules in the contrib space. almost finished and then work can continue

**Comment by jenlampton** [comment] 2016-02-04 18:46
That's fantastic @earthday47 thank you! :)

**Comment by earthday47** [comment] 2016-02-04 18:56
ok attn @gifad @quicksketch @jenlampton 

I took gifad's backdrop-geokit project and split it into four modules, which are now on backdrop-contrib:

- Geocoder (https://github.com/backdrop-contrib/geocoder)
- Geofield (https://github.com/backdrop-contrib/geofield)
- geoPHP (https://github.com/backdrop-contrib/geophp)
- Leaflet (https://github.com/backdrop-contrib/leaflet)

I decided to nest the two add-on modules for leaflet into the project themselves under `contrib/` folder. They are `leaflet_markercluster` and `leaflet_more_maps`.

I kept the version history from Drupal, added LICENSE.txt and README.md, and removed some commented code. Tried to get the minimum so they are in accord with Backdrop CMS project standards.

I have not yet personally installed these modules and run them locally, so that'll be a good QA step.

In terms of what I can provide, I won't be able to do too much deep-diving into the code for these, but I am happy to facilitate the backdrop-contrib code and keeping things moving. gifad can make pull requests to each project as needed and I'll be happy to merge in.

go teamz :horse_racing:

**Comment by jenlampton** [comment] 2016-02-04 18:59
This is wonderful, a great start - thank you again!

@gifad that means your project application now becomes a request for co-maintainership with @earthday47 on for these projects.  For that, we require an endorsement from an already-approved contrib group member. 

Since the last comment by @earthday47 sounds like an endorsement for comaintainership, @klonos can you please give @gifad access to the contrib repo?

**Comment by gifad** [comment] 2016-02-04 22:21
I'm really glad that you made my work (hopefully) usefull, thanks
> Playtime has officially begun ;)

Two topics should be clarified before we dive in code, though

1. The "version history from Drupal" extends beyond the state this port has been done from; this is probably not important, except for [Geocode from virtual fields / entity property instead of just real fields](https://github.com/backdrop-contrib/geocoder/commit/59548f1d3a843bbbdb90ba0b3155d692ee1cd05b) which looks promising, but starts with `entity_get_all_property_info()` which belongs to drupal7 Entity API module, which was not fully ported to  backdrop...

2. The leaflet port is a customized version, which integrates 3 or 4 leaflet plugins - this implied patches in leaflet.module and js. Should we remove them (and document how to re-insert), or just ship the related libraries ? It seems to be prohibited by backdrop, but there is a notable exception made for CKEditor...

**Comment by jenlampton** [comment] 2016-02-04 22:26
> starts with entity_get_all_property_info() which belongs to drupal7 Entity API module, which was not fully ported to backdrop...

Entity API does not need to be ported because we included much of it in core. Check for a similar / comparable API function to `entity_get_all_property_info` in Backdrop itself. (Sometimes you may need to use two different functions to achieve the same ends...)

> ship the related libraries ? It seems to be prohibited by backdrop...

It was prohibited by Drupal, but it is allowed in Backdrop. Feel free to package libraries where needed.

**Comment by gifad** [comment] 2016-02-04 23:07
> It was …

In english, this is "present perfect", isn't it ? interesting...

Could you point me to the guidelines describing the package layout to use (or a current contrib project that includes libraries - Colorbox does not...)

**Comment by jenlampton** [comment] 2016-02-04 23:25
flexslider does: https://github.com/backdrop-contrib/flexslider

**Comment by klonos** [comment] 2016-02-05 14:26
> @klonos can you please give @gifad access to the contrib repo?

Done! ...made him a member and also added him to the "Authors" team.

**Comment by klonos** [comment] 2016-02-05 14:28
@gifad your invitation is underway. Let me/us know if you have any issues with permission/access. Welcome!

**Comment by opi** [comment] 2017-10-05 09:34
Note that I ported the simple *geolocation field* module : https://github.com/opi/geolocation
Related issues:
- https://github.com/backdrop-ops/contrib/issues/238
- https://www.drupal.org/node/2914022

**Comment by klonos** [comment] 2019-08-30 18:04
I believe that it's safe to close this one.

**Closed by klonos** 2019-08-30 18:04 UTC
Labels: Maintainer application, Port in progress
