### ISSUE TITLE
Requesting permission to contribute!

### ISSUE THREAD

**Issue by Drupal8Todd** [backdrop-ops/contrib#117] opened 2015-11-02 17:00 UTC
I am writing a new book for Apress on Backdrop and have ported the Honeypot module and will be porting other D7 modules to support my clients' move to Backdrop.

**Comment by quicksketch** [comment] 2015-11-03 05:48
Hi @Drupal8Todd! Excellent! Welcome aboard and we're thrilled to hear you'll be authoring a book on Backdrop (you may be the first!)

Per our normal review policy, could you put your port of the Honeypot module up in your personal GitHub account for a basic review? All projects must meet these minimum requirements.

- [ ] Include a LICENSE.txt file that indicates the code is GPL v2. You can use [this copy](https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/LICENSE.txt).
- [ ] Include a README.md file that includes license and maintainer information. You can use [this example](https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/README.md).
- [ ] Maintain the Git history from Drupal 7. See [this article](http://tag1consulting.com/blog/how-maintain-contrib-modules-drupal-and-backdrop-same-time-part-2).

**Comment by quicksketch** [comment] 2015-11-03 05:55
Hm, it looks like Honeypot is already ported though! See https://github.com/backdrop-contrib/honeypot and https://backdropcms.org/project/honeypot. If you're interested in helping maintain the module, you could post an issue to that module's issue queue.

We're more than happy to have additional contributors however! There are still lots of projects that could use porting, for example:

- https://www.drupal.org/project/diff
- https://www.drupal.org/project/page_title
- https://www.drupal.org/project/node_clone
- https://www.drupal.org/project/charts

Just some ideas! We'd love to have your help. :smile:

**Comment by Drupal8Todd** [comment] 2015-11-03 14:27
Ah thanks Nate -- It worked as a great example in porting a Drupal module
to Backdrop.  That chapter is already submitted and approved so I'll stick
with what I did.

**Comment by Drupal8Todd** [comment] 2015-11-08 22:41
Hi Nate and crew.  I'm working on a chapter in my Backdrop book that walks
through migrating a Drupal 7 site to Backdrop but ran into an issue
following the directions on the Backdropcms.org site.  The configuration
directory is empty when I follow the directions and I'm getting an error
that is preventing me from moving forward with the migration.  My work
around was to install a second copy of Backdrop in a second directory and
to copy all of the configuration files into the config_xxxxxxxxx/active
directory.   I'm not sure if that's the intended approach?   Any hints
would be greatly appreciated.  I don't want to mislead the community.

Todd Tomlinson
Author Apress Publishing

**Comment by quicksketch** [comment] 2015-11-09 07:28
Hi @Drupal8Todd! I'm more than happy to help with anything you need. In fact if you need a technical reviewer I'd love to help in that regard. On this particular question:

> The configuration directory is empty when I follow the directions and I'm getting an error that is preventing me from moving forward with the migration.

Which instructions did you follow?

> The configuration directory is empty when I follow the directions and I'm getting an error that is preventing me from moving forward with the migration. 

What error are you receiving?

>  My work around was to install a second copy of Backdrop in a second directory and to copy all of the configuration files into the config_xxxxxxxxx/active directory. I'm not sure if that's the intended approach?

In order to move configuration from one site to another, you must first have Backdrop installed on both sites. If you want to just clone a site, you can copy both the "active" config directory and the entire database (via mysqldump and mysql importing) to the second site.

If you want to just move the configuration (such as when deploying a feature from dev to live), then copy the contents of the "active" directory on dev to the "staging" directory on the live server. Then visit `admin/config/development/configuration` to import the configuration. You must run the import through the UI, as Backdrop may need to adjust/create database tables based on the configuration (such as when adding a new field).

**Comment by Drupal8Todd** [comment] 2015-11-09 15:02
Hi Nate -- I followed the directions here:
https://backdropcms.org/upgrade-from-drupal

Apress assigned a technical reviewer but wonder if you would be willing to
write the intro to the book?   Dries wrote the intro to my Pro Drupal 7
development book.   If so let me know and I'll get you what Apress is
looking for.   They see this book as a test to see if there's a market for
Backdrop books.

I'm super impressed with the platform, you've done an amazing job and its
the right answer for a vast majority of my clients.  Thank you for having
the vision!

Todd

**Comment by quicksketch** [comment] 2015-11-09 19:57
> Apress assigned a technical reviewer but wonder if you would be willing to write the intro to the book?

Certainly, I'd love to do that. As this is the first Backdrop book that will be published (AFAIK) I'd love to give a (very) basic intro to Backdrop and why it exists.

Writing a book is a lot of work, so I appreciate everything you're putting into it! If you need additional technical direction, please ask when needed. As Backdrop has only existed for a short while, there may be areas where there really isn't anywhere else to go but to the source, so I'm really glad to see you asking questions here. :)

I'll need to run through the upgrade myself manually to see if I can reproduce any issues. We have tests that cover upgrading, but it's not identical to running it through the UI. On your D7 site that you're upgrading, have you installed any contrib modules, or it just core that you're upgrading?

**Comment by Drupal8Todd** [comment] 2015-11-09 20:22
Hi Nate,


Apress said they would love it if you would write an intro  to the book.
They are trying to have the book on shelves before the end of the year.
The deadline to have the book through editorial is Nov 15th.   If you have
something you can send my way I'll make sure that Apress has the
information.  I'll cc Ben Renow-Clarke on the email.  Ben is the web
development editor for Apress and has been the editor on all 4 of my
books.

For the demo site that I migrated I took a stock off-the-shelf D7 site, ran
Devel generate to create content, and ran through the steps outlined on the
site.  Everything worked perfectly with the exception of an error that the
config_xxxxxxx/active directory being empty.   It was a hard error, meaning
the site didn't render.   Once I copied a default set of config files from
a base install of Backdrop the site rendered and I was able to run
update.php.   Everything ran perfectly from that point.

**Comment by quicksketch** [comment] 2015-11-10 05:07
Okay thanks @Drupal8Todd, I'll see if I can reproduce by following the steps. Shoot me an email nate@quicksketch.org.

**Comment by Drupal8Todd** [comment] 2015-11-18 13:44
Hi Nate,

It’s good to meet you. Please do let me know if this is something that you’d like to do. I’m afraid time is very tight now, so we’d really need something today if you do want to contribute a foreword.

I look forward to hearing from you.

Cheers,

Ben

**Comment by jenlampton** [comment] 2015-11-25 04:50
Hi Todd, Did you ever hear back from Nate? I hope that you were able to reach him at his email and that you got a nice intro for your book.  I also look forward to reading it, and wanted to also thank you personally for taking the time and effort :)

**Comment by Drupal8Todd** [comment] 2015-11-25 14:03
Hi Jen, Apress reached out but didn't hear back and we passed the deadline.  The book should be on the shelves by Dec 15th!

**Comment by jenlampton** [comment] 2015-12-09 23:26
I'm so excited!  Thank you so much for working on it :)

**Comment by klonos** [comment] 2019-08-30 17:56
I think it's safe to close this one. Thanks for working on the Backdrop book @Drupal8Todd 👍

**Closed by klonos** 2019-08-30 17:56 UTC
Labels: Maintainer application
