### ISSUE TITLE
Contrib Group Application: gto1 + several modules

### ISSUE THREAD

**Issue by gto1** [backdrop-ops/contrib#736] opened 2023-12-05 20:04 UTC
Hello and welcome to the contrib application process! We're happy to have you :)

**Please indicate how you intend to help the Backdrop community by joining this group**
* Option 1: I would like to contribute a project

## Based on your selection above, please provide the following information:

**The name of your modules:**

Image Class
Webform Scheduler
Views Merge Rows
Views Field Formatter

##Please note these 3 requirements for new contrib projects:

- [x] Include a README.md file containing license and maintainer information.
      You can use this example: https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/README.md
- [x] Include a LICENSE.txt file.
      You can use this example: https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/LICENSE.txt.
- [x] If porting a Drupal 7 project, Maintain the Git history from Drupal.

**Post a link here to an issue in the drupal.org queue notifying the Drupal 7 maintainers that you are working on a Backdrop port of their project**

I still need to do this.

**If you have already contributed code to Backdrop core or contrib projects, please provide 1-3 links to pull requests or commits**
The completed/ported modules are in a private Gitlab repo at this time.

**If you have chosen option 2 or 1 above, do you agree to the [Backdrop Contributed Project Agreement](https://github.com/backdrop-ops/contrib#backdrop-contributed-project-agreement)**
YES

**Comment by jenlampton** [comment] 2023-12-14 21:37
Hi @gto1, and welcome to Backdrop contrib! We're thrilled to have you, and looking forward to your contributions. 

In order to verify the 3 requirements for a new contrib project, we'll need to see any one of your 4modules in a public GitHub repository (but not all of them!). Could you copy one of them over for our review? 

Below is how I do it for my existing projects:

1. Go to https://github.com/new in your browser, and create a new repository with the same name, for example: `image_class`
2. Copy the clone URL, for example: `git@github.com:gto1/image_class.git`
3. Navigate into the Git root for the existing project
4. Add a second remote, for example: `git add remote upstream git@github.com:gto1/image_class.git`
5. Push the current code up to the new remote, for example: `git push upstream`
6. Then past the URL for the project here, for example: `https://github.com/gto1/image_class`

**Comment by gto1** [comment] 2023-12-14 22:38
Thanks Jen! Excellent, I'll share one of the modules first thing tomorrow.

**Comment by gto1** [comment] 2023-12-15 17:54
https://github.com/gto1/image_class/tree/1.x-1.x

**Comment by gto1** [comment] 2023-12-15 18:45
https://github.com/gto1/views_field_formatter
https://github.com/gto1/views_merge_rows
https://github.com/gto1/webform_scheduler

**Comment by jenlampton** [comment] 2023-12-15 21:55
##Please note these 3 requirements for new contrib projects:

- [x] Include a README.md file containing license and maintainer information.
      You can use this example: https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/README.md
- [x] Include a LICENSE.txt file.
      You can use this example: https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/LICENSE.txt.
- [x] If porting a Drupal 7 project, Maintain the Git history from Drupal.

Thanks @gto1! The image_class project meets all the requirements for joining contrib, so an invite is on the way :)

**Comment by jenlampton** [comment] 2023-12-15 22:46
I also did a quick code review, and everything looks really good!

I have only very minor notes -- Items in this comment are only suggestions, take or leave them as you please. We do this review specifically looking for things that may be done differently between Backdrop and Drupal in the hopes that this information might help with the transition for those new to Backdrop :)

### `README.md` suggestions

- For the section on Issues, it would be helpful if "the issue queue" was linked to the specific GitHub queue for this module (I assume you are already planning to do this once the link to the queue is confirmed, but still noting it here just in case)
- Please use a URL to a GitHub profile for all current maintainers.
- If possible, please link the names directly in the Credits section, rather than printing the complete URL. For example: `Ported to Backdrop CMS by Greg OToole https://github.com/gto1` would become 
`Ported to Backdrop CMS by [Greg OToole](https://github.com/gto1)`

### `.info` file suggestions

- In [views_merge_rows.info](https://github.com/gto1/views_merge_rows/blob/1.x-1.x/views_merge_rows.info) there are quotation marks around the package that aren't necessary (but also aren't problematic)
- Several modules list Views as a dependency `dependencies[] = views`. This is not strictly necessary anymore, because Views is not a module that can be disabled in Backdrop. The Views module is both required and hidden, because it runs nearly all of our administration listings. (but even so, I usually leave this line in my views modules too!)

### Location of files in the module

- Files that contain PHP classes should be placed into an `/includes/` subdirectory. This makes it easier for developers to scan the list of files and directories in a module and immediately know the module contains classes, without even needing to open any files. In the case of[views_merge_rows_plugin_display_extender.inc]( https://github.com/gto1/views_merge_rows/blob/1.x-1.x/views_merge_rows_plugin_display_extender.inc) it would be the only file in the directory, but we do still recommend placing it there for consistency across modules.

## General coding standards

- Blank lines after the opening `<?php` tag could be removed (if you want). The extra line breaks were required in Drupal because of the previous CVS version control system, but are not needed anymore.
- For new functions, `@params` and `@return` should appear in the docblock. (This is not necessary for hook implementations.)

## Module specific suggestions

- There's a function definition for `boolval()` in [views_field_formatter.module](https://github.com/gto1/views_field_formatter/blob/1.x-1.x/views_field_formatter.module) that's docblock indicates that it is for PHP versions less than 5.5 - but the minimum required version for Backdrop CMS is PHP 5.6 -- so this can safely be removed.

**Comment by gto1** [comment] 2024-01-12 20:36
Hi @jenlampton Thanks. Is anything else needed from me here (other than these optional suggestions)? Not sure what the next steps are. I can certainly do some of these clean-up suggestions here.

**Comment by jenlampton** [comment] 2024-01-13 01:17
@gto1 nothing else is needed, you are a valued member of the contrib group!

The only next step is to [transfer the repository](https://docs.backdropcms.org/documentation/after-your-application-is-accepted) into the contrib group. You can ask here if you have questions while doing so, and when you are done, we can close this issue 🎉

**Comment by gto1** [comment] 2024-01-13 14:51
Thanks @jenlampton I'm working on transferring the repos and got this message.
<img width="890" alt="Screenshot 2024-01-13 at 9 50 14 AM" src="https://github.com/backdrop-ops/contrib/assets/827990/5a745670-9ae5-45cf-ad25-64fbb5e1cd2f">

**Comment by jenlampton** [comment] 2024-01-15 21:09
@gto1 It looks like the invitation we sent you had expired. Please check your inbox for a message from GitHub, and follow the instructions to join the group. Once you are a member you will be able to transfer the repository.

**Comment by gto1** [comment] 2024-01-16 17:11
Great, thanks, just accepted the new invite.

**Comment by jenlampton** [comment] 2024-03-21 21:04
I'm going to mark this issue as resolved, but if you have any questions @gto1  feel free to still ask here or open a new issue.

**Closed by jenlampton** 2024-03-21 21:04 UTC
Labels: Port in progress, Maintainer application
