### ISSUE TITLE
Ported Menu Export/Import module

### ISSUE THREAD

**Issue by VasasA** [backdrop-ops/contrib#324] opened 2019-03-17 23:12 UTC
I ported Menu Export/Import module to Backdrop 1.12.4.
I used these guides:
https://api.backdropcms.org/converting-modules-from-drupal
https://www.lullabot.com/articles/porting-drupal-7-modules-to-backdrop

Finally I setted the "backdrop_drupal_compatibility" to FALSE in the Backdrop's settings.php, and the modul worked properly.
Original Drupal 7 modul: 
https://www.drupal.org/project/menu_import
Ported Backdrop modul: 
https://github.com/VasasA/menu_import

Will anybody publish this modul on https://backdropcms.org/project/menu_import ? :)
Thank!
VasasA (Hungary)

**Comment by herbdool** [comment] 2019-03-18 17:17
Thanks @vasasA! @klonos will be able to approve your application once everything is confirmed. I don't have that power but I can make suggestions for making sure the code meets Backdrop standards.

**Comment by herbdool** [comment] 2019-03-18 17:33
Code fixes:

* In the .info file remove the version and datestamp as those will be generated automatically with a release.
* Rename to README.md
* The README file needs additional sections: License, Maintainers and Credits. For example https://github.com/backdrop-contrib/project/blob/1.x-1.x/README.md
* First part of README should be module name and can remove $id.
* Put the .test file into the tests folder and create a menu_import.tests.info file to list the test classes (see https://github.com/backdrop-contrib/webform/tree/1.x-4.x/tests for example)
* Do not need autoload_info hook for test classes. The .tests.info file will load them and we don't want to load them all the time.
* You need to maintain the Drupal 7 git history. Looks like you are missing it.
* Default branch should be 1.x-1.x with the second number matching Drupal 7's.
* hook_help is no longer available in Backdrop.

I haven't tested the module itself but the rest seems ok.

I think you're close to being ready.

**Comment by klonos** [comment] 2019-03-18 18:56
Hello @VasasA and thanks for porting the module! 👍

Also thanks @herbdool for the thorough review 👍

@VasasA once you have addressed @herbdool's feedback, here's the minimum requirements your project must meet before being accepted in backdrop-contrib:

- [ ] If porting a Drupal project, Maintain the Git history from Drupal 7. See
    [this article](http://tag1consulting.com/blog/how-maintain-contrib-modules-drupal-and-backdrop-same-time-part-2).
- [ ] Include a README.md file that includes license and maintainer information.
    You can use [this example](https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/README.md).
- [x] Include a LICENSE.txt file that indicates the contributed code is GPL-2.0
    (or in rare cases GPL-3.0 -- please see below). Please use [this text for GPL-2.0](https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/LICENSE.txt).

Please let us know if you require any help with these.

**Comment by VasasA** [comment] 2019-03-20 11:28
Dear @herbdool and @klonos,
Thanks a lot for your help! It was very useful. I done all steps, and pushed to the repo. I hope it's right.
What will my next task be?

**Comment by herbdool** [comment] 2019-03-20 11:57
Thanks again!

A couple small fixes:

* If you use back ticks around code to have it format properly. https://guides.github.com/features/mastering-markdown/
* Under credits the link your user needs to be fixed.

I'll take a quick look at rest soon.

**Comment by herbdool** [comment] 2019-03-20 12:16
One more: no longer need the getInfo() function in the test classes since that is now in .tests.info.

My suggestions shouldn't hold up your module being accepted.

**Comment by VasasA** [comment] 2019-03-20 23:51
Thank, I learn a lot from You! I've done the suggested steps.

**Comment by VasasA** [comment] 2019-03-23 09:17
Dear @klonos,
I think this modul is ready to publis maybe. 
https://github.com/VasasA/menu_import
What will my next task be?

**Comment by klonos** [comment] 2019-03-25 19:58
Good job @VasasA 👍 ...last thing: I need you to officially reply to say that you agree with the [Backdrop Contributed Project Agreement](https://github.com/backdrop-ops/contrib#backdrop-contributed-project-agreement)

**Comment by VasasA** [comment] 2019-03-26 09:29
Thank You @klonos! I agree with the [Backdrop Contributed Project Agreement](https://github.com/backdrop-ops/contrib#backdrop-contributed-project-agreement)

**Comment by klonos** [comment] 2019-03-26 21:18
...I have actually jumped the gun and had already sent you an invite to join the backdrop-contrib group (I knew you'd agree 😄):

> You've invited Attila Vasas to Backdrop CMS contributed projects! They'll be receiving an email shortly. They can also visit https://github.com/backdrop-contrib to accept the invitation.

Welcome onboard 🎉 😄 

...once you have moved your project over to backdrop, you should be able to create releases on GitHub, which will automatically create release nodes on backdropcms.org, which will in turn allow the module to show up and installed via the Project Browser 😉

**Comment by klonos** [comment] 2019-03-26 21:20
I will go ahead and close this issue, but please feel free to let us know if you are having any problem. Preferred channel for more speedy response is via Gitter: https://gitter.im/backdrop/backdrop-issues

**Closed by klonos** 2019-03-26 21:20 UTC
Labels: Maintainer application, Port in progress

**Comment by VasasA** [comment] 2019-03-27 12:25
I'm glad I'm in the group. :smile: I followed the guides, and published a release:
https://backdropcms.org/project/menu_import
It's a nice day for me. :smile: I hope I will be an useful contributor for Backdrop CMS in the future. :blush:
Thank all of You!

**Comment by klonos** [comment] 2019-03-27 19:26
Thanks @VasasA 😄 

One think you might want to consider is using semantic versioning for your releases. So 1.x-1.7.0 instead of 1.x-1.7.
