### ISSUE TITLE
Application to join:  dyrer (Flat Zymphonies Theme)

### ISSUE THREAD

**Issue by dyrer** [backdrop-ops/contrib#176] opened 2016-09-01 22:28 UTC
I am porting  flat_zymphonies_theme with @klonos https://github.com/dyrer/flat_zymphonies
I also requested permissions   @@https://www.drupal.org/node/2793919

**Comment by klonos** [comment] 2016-09-01 22:30
...repo currently at https://github.com/dyrer/flat_zymphonies

**Comment by klonos** [comment] 2016-09-01 22:31
New project checklist
---------------------

All projects must meet these minimum requirements.

- [ ] Include a LICENSE.txt file that indicates the code is GPL v2. You can use
[this copy](https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/LICENSE.txt).
- [ ] Include a README.md file that includes license and maintainer information.
You can use [this example](https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/README.md).
- [ ] Maintain the Git history from Drupal 7. See
[this article](http://tag1consulting.com/blog/how-maintain-contrib-modules-drupal-and-backdrop-same-time-part-2).

**Comment by jenlampton** [comment] 2020-01-31 01:27
I think [an older issue](https://github.com/backdrop-ops/contrib/issues/122) was a duplicate of this one, so I've closed that one in favor of this one. @dyrer please let us know if you need any assistance!

**Comment by klonos** [comment] 2023-02-09 11:59
Hey @dyrer 👋🏼 ...it's been a while since we heard from you, so I will go ahead and close this issue here.

Please feel free to reopen if you are still interested.

**Closed by klonos** 2023-02-09 11:59 UTC
Labels: Port in progress, Maintainer application
