### ISSUE TITLE
Problem README on backdropcms.org

### ISSUE THREAD

**Issue by rhoscalas** [backdrop-ops/contrib#152] opened 2016-03-18 17:16 UTC
I created the first release for the MathJax module, but the readme on backdropcms.org does not match with the correct readme!

**Comment by klonos** [comment] 2016-03-18 22:43
I see the issue. It's picking up the last part of the readme somehow.

The only thing that I can think of that your project is doing differently from the others is that it has a hyphen in its name while others use underscores. @quicksketch, @jenlampton could this be it?

@rhoscalas whatever the cause of the issue, I think that the machine name of your project should be changed. It is currently `mathjax-backdrop` but I think that the "backdrop" part is superfluous. None of the other contrib projects ported from Drupal have the `-backdrop` suffix added to their names. Unfortunately, this might mean that you'll have to recreate the whole repository, but I'm not entirely sure. Again, @quicksketch, @jenlampton, anybody else??

**Comment by jenlampton** [comment] 2016-03-18 22:46
I don't understand how a module name would affect the readme parsing, but having a hyphen in the name will definitely be problematic. Perhaps fix that first, and see if the other problems remain?

**Comment by rhoscalas** [comment] 2016-03-19 10:24
I completely agree with the fact that the hyphen is superfluous. How can I fix that? I don't have sufficient permissions to rename the module. Thanks in advance! I am sorry for this inconvenience..

**Comment by klonos** [comment] 2016-03-19 21:08
@rhoscalas I'm sorry but my GitHub knowledge is not that good in order to help you with renaming (or to even know if that is possible at all). We'll have to wait for someone with more know-how.

Just to point out though that it is not only the hyphen that needs to be removed. The entire `-backdrop` suffix needs to go.

**Comment by klonos** [comment] 2016-03-19 21:14
...everything in your folder structure needs to match the project name AFAIK, but for example while your project name is `mathjax-backdrop`, your .info file is `mathjax.info` and inside it you have references to `mathjax` like `admin/config/content/mathjax` and `mathjax.test` (not `mathjax-backdrop`). So, this whole situation might be the cause of things.

**Comment by rhoscalas** [comment] 2016-03-19 23:01
Yes I agree with you @klonos! My mistake was to give the mathjax-backdrop name. I would have had to rename it before transferring on backdrop-contib, but I forgot unfortunately.. This is my first time I use github, I'm sorry.

**Comment by jenlampton** [comment] 2016-03-20 01:15
I have renamed the repo: https://github.com/backdrop-contrib/mathjax 
Hope that's okay :)

**Comment by klonos** [comment] 2016-03-20 02:29
Thanx @jenlampton :+1: 

I believe next steps are:

1. Delete the MathJax node created on b.org. I'm not sure if simply changing the node path to 'https://backdropcms.org/project/mathjax' (remove the `-backdrop` suffix) would work 100%. Although the "Download 1.x-1.0.0" and "Notes" links GitHub do work (github redirect magic I guess?).

2. Delete the 1.0.0 release and create a new one with the same version because the package for the current one has the `-backdrop` suffix in the .zip file and the .zip file itself has a folder within it that also has a `-backdrop` suffix.

So I think that deleting the node project from b.org and then the release would be best. Creating a new release would trigger the creation of a proper .zip file and also the creation of a new project node in b.org.

Task 1 needs to be done either by you @jenlampton or @quicksketch I guess due to b.org permissions, but task 2 can be done by @rhoscalas BUT they need to be done in that order. So wait for task 1 to be completed first.

**Comment by jenlampton** [comment] 2016-03-20 03:16
I've taken care of #1 Delete the MathJax node created on b.org. 

@rhoscalas do you want to handle #2?

**Comment by rhoscalas** [comment] 2016-03-20 13:11
Ok, done! @jenlampton @klonos I have followed steps 1 and 2. The new release is 1.0.0 as the first one I have created. It is now ok? Thanks for the help @jenlampton @klonos

**Comment by rhoscalas** [comment] 2016-03-20 14:27
It is all ok on /node/568 @jenlampton @klonos, but now there is a small problem with the alias /project/mathjax.

**Comment by klonos** [comment] 2016-03-20 23:24
I think that everything is fixed now @rhoscalas 

> but now there is a small problem with the alias /project/mathjax.

What problem exactly?

**Comment by rhoscalas** [comment] 2016-03-21 08:54
Now it works all right!! Yesterday I found a problem with the access on /project/mathjax, but today is working all fine. Thanks so much @klonos and you all!!

**Comment by klonos** [comment] 2016-03-21 09:00
You're welcome @rhoscalas Thank you for porting this module.

Lets close this issue then.

**Closed by klonos** 2016-03-21 09:00 UTC
